### ISSUE TITLE
What will be the License?

### ISSUE THREAD

**Issue by jerger** [dschaefer/eclipse-two#1]
Hi, 

I'm creating installation routines for local or remote ide setups (http://www.agileventures.org/projects/dda-pallet). So I'm always searching for cool new ide concepts :-). 
May I ask, if you've already thought about a License?

BR, jerger

**Comment by dschaefer** [comment]
Since this is intended to be an Eclipse project, it is licensed with the Eclipse Public License 1.0. I have put a LICENSE file in to highlight that and updated the copyrights of yesterday's submissions that were missing it.

**Comment by jerger** [comment]
great - thanks :-)
