### ISSUE TITLE
Cannot read property 'config' of undefined  in Monaco.ts

### ISSUE THREAD

**Issue by gravemalte** [dschaefer/eclipse-two#14]
Hey there,

found an strange error in Monaco.ts.

```ts
loader.require.config({
    baseUrl: baseUrl
});
````

This line of code does not allow to start eclipse-two respectively gives an error in the dev tools and the editor cannot start. 
![image](https://cloud.githubusercontent.com/assets/22529605/22845137/702a70a4-efe1-11e6-8f95-65778568f1ca.png)

After removing this line all works fine.

Hope I could help :)

Greetings

**Comment by dschaefer** [comment]
Uh, I see it now. Had to clean out my node_modules and dist. Thanks! This loader.require thing has been a pain in the ...

**Comment by gravemalte** [comment]
I see. It's a pleasure to contribute to the project !

**Comment by dschaefer** [comment]
Can't wait to get it to a state where I can get even more contributions :).

Fixed. Must have been an API change in the latest Monaco update. Glad I have VS.Code as an example of how to load this thing!
