### ISSUE TITLE
cannot install types\three

### ISSUE THREAD

**Issue by buddybu** [dschaefer/eclipse-two#6]
Ran npm install just after cloning and received this failure:

npm http 404 https://registry.npmjs.org/types/three
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'types/three' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'eclipse-two'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\ProgramData\\chocolatey\\lib\\nodejs.commandline\\tools\\node.exe" "C:\\ProgramData\\chocolatey\\lib\\npm\\too
ls\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd G:\proj\eclipse-two
npm ERR! node -v v5.10.1
npm ERR! npm -v 1.4.9
npm ERR! code E404

**Comment by dschaefer** [comment]
My first guess is that you have a very old installation of node and npm. My npm -v shows version 3.10.9. This @types thing is pretty new so I'd suggest upgrading first and let me know if that helps.

**Comment by buddybu** [comment]
That was it.  NPM showed version 1.4.9.  Now I am running 4.0.5

Maybe a version requirement (or suggestion that it must be newer than 3.10.9) as part of the README.md

**Comment by dschaefer** [comment]
I'm not sure what the version requirement is, but I'll add something.
